#ifndef ALD_VERSION_INCLUDED
#define ALD_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define ALD_VERSION_MAJOR	1
#define ALD_VERSION_MINOR	2
#define ALD_VERSION_PATCH	0
#define ALD_VERSION_BETA	0
#define ALD_VERSION_VERSTRING	MAKE_STR(ALD_VERSION_MAJOR) "." MAKE_STR(ALD_VERSION_MINOR) "." MAKE_STR(ALD_VERSION_PATCH) "." MAKE_STR(ALD_VERSION_BETA)

#endif